# Generated by Django 3.1.6 on 2021-03-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pola', '0007_auto_20180527_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='no_of_new_reports',
        ),
        migrations.AddField(
            model_name='stats',
            name='no_of_new_reports_reported_by_bot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='no_of_new_reports_reported_by_users',
            field=models.IntegerField(default=0),
        ),
    ]
